const mongoose = require('mongoose')
const Vote = require('../models/vote')

mongoose.connect('mongodb://localhost/bbc', (err, db) => {
  //Delete all database data
  db.dropDatabase()
    .then(() => Vote.create(
      [{
        email: 'begona@example.com',
        candidate: 1
      }, {
        email: 'begona@example.com',
        candidate: 2
      }, {
        email: 'begona@example.com',
        candidate: 3
      }, {
        email: 'begona2@example.com',
        candidate: 1
      }, {
        email: 'begona2@example.com',
        candidate: 4
      }, {
        email: 'begona2@example.com',
        candidate: 5
      }, {
        email: 'begona3@example.com',
        candidate: 1
      }, {
        email: 'begona3@example.com',
        candidate: 2
      }, {
        email: 'begona3@example.com',
        candidate: 3
      }, {
        email: 'begona4@example.com',
        candidate: 4
      }, {
        email: 'begona4@example.com',
        candidate: 4
      }, {
        email: 'begona4@example.com',
        candidate: 3
      }, {
        email: 'begona5@example.com',
        candidate: 5
      }, {
        email: 'begona5@example.com',
        candidate: 2
      }, {
        email: 'begona5@example.com',
        candidate: 1
      }, {
        email: 'begona6@example.com',
        candidate: 5
      }, {
        email: 'begona6@example.com',
        candidate: 3
      }, {
        email: 'begona6@example.com',
        candidate: 3
      }, {
        email: 'begona7@example.com',
        candidate: 5
      }, {
        email: 'begona7@example.com',
        candidate: 4
      }, {
        email: 'begona7@example.com',
        candidate: 1
      }, {
        email: 'begona8@example.com',
        candidate: 1
      }, {
        email: 'begona8@example.com',
        candidate: 2
      }, {
        email: 'begona8@example.com',
        candidate: 3
      }, {
        email: 'begona9@example.com',
        candidate: 1
      }, {
        email: 'begona9@example.com',
        candidate: 2
      }, {
        email: 'begona9@example.com',
        candidate: 3
      }, {
        email: 'begona10@example.com',
        candidate: 1
      }, {
        email: 'begona10@example.com',
        candidate: 1
      }, {
        email: 'begona10@example.com',
        candidate: 1
      }, {
        email: 'begona11@example.com',
        candidate: 1
      }, {
        email: 'begona11@example.com',
        candidate: 2
      }, {
        email: 'begona11@example.com',
        candidate: 3
      }, {
        email: 'begona12@example.com',
        candidate: 2
      }, {
        email: 'begona12@example.com',
        candidate: 2
      }, {
        email: 'begona12@example.com',
        candidate: 2
      }, {
        email: 'begona13@example.com',
        candidate: 3
      }, {
        email: 'begona13@example.com',
        candidate: 3
      }, {
        email: 'begona13@example.com',
        candidate: 3
      }, {
        email: 'begona14@example.com',
        candidate: 4
      }, {
        email: 'begona14@example.com',
        candidate: 4
      }, {
        email: 'begona14@example.com',
        candidate: 4
      }, {
        email: 'begona15@example.com',
        candidate: 5
      }, {
        email: 'begona15@example.com',
        candidate: 5
      }, {
        email: 'begona15@example.com',
        candidate: 5
      }, {
        email: 'begona16@example.com',
        candidate: 3
      }, {
        email: 'begona16@example.com',
        candidate: 3
      }, {
        email: 'begona16@example.com',
        candidate: 3
      }, {
        email: 'begona17@example.com',
        candidate: 1
      }, {
        email: 'begona17@example.com',
        candidate: 1
      }, {
        email: 'begona17@example.com',
        candidate: 1
      }, {
        email: 'begona18@example.com',
        candidate: 4
      }, {
        email: 'begona18@example.com',
        candidate: 4
      }, {
        email: 'begona18@example.com',
        candidate: 4
      }, {
        email: 'begona19@example.com',
        candidate: 3
      }, {
        email: 'begona19@example.com',
        candidate: 3
      }, {
        email: 'begona19@example.com',
        candidate: 3
      }, {
        email: 'begona20@example.com',
        candidate: 2
      }, {
        email: 'begona20@example.com',
        candidate: 2
      }, {
        email: 'begona20@example.com',
        candidate: 2
      }, {
        email: 'begona21@example.com',
        candidate: 1
      }, {
        email: 'begona21@example.com',
        candidate: 1
      }, {
        email: 'begona21@example.com',
        candidate: 1
      }, {
        email: 'begona22@example.com',
        candidate: 2
      }]
    ))
    .then(() => console.log('Database successfully seeded'))
    .catch(err => console.log(err))
    .finally(() => mongoose.connection.close())
})
